apiVersion: v1
kind: Secret
metadata:
  name: quay-io-credentials
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhbUZ6Y0dGMWJGOXJhSFZ5WVc1aFgybGliU3R4ZFdGNVgybHZYMk55WldSbGJuUnBZV3h6T2pCTFdrVlpTRVpWUms5S016aFNTRk5IUzBaTVJ6VXpVRkZZVVRFMU5FZzJWVkEyT0ZKQlVsaExNVkpGUTBnMVZWUXpTVVZZTTFVMVJrOVFPRlZJVnpnPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson